name: Pipeline
on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - uses: actions/checkout@v4

      - name: fmt
        run: |
          issues=$(gofmt -l .)
          echo "$issues"
          test -z "$issues"

      - name: vet
        run: |
          go vet $(go list ./... | grep -v /vendor/)

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  vuln:
    name: vuln
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
      - uses: actions/checkout@v4
      - name: vuln
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
